version: '3.1'
services:
  springboot:
    image: chowdaiah028/testing:maven-web-application1
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
